// حالات سير العمل
const WORKFLOW_STATES = {
  STARTED: 'started',
  IN_PROGRESS: 'in_progress',
  DELIVERED: 'delivered',
  REVIEWED: 'reviewed',
  APPROVED: 'approved',
  REJECTED: 'rejected'
};

// التحولات المسموحة بين الحالات
const VALID_TRANSITIONS = {
  [WORKFLOW_STATES.STARTED]: [WORKFLOW_STATES.IN_PROGRESS, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.IN_PROGRESS]: [WORKFLOW_STATES.DELIVERED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.DELIVERED]: [WORKFLOW_STATES.REVIEWED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.REVIEWED]: [WORKFLOW_STATES.APPROVED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.APPROVED]: [],
  [WORKFLOW_STATES.REJECTED]: [WORKFLOW_STATES.STARTED]
};

// أدوار المستخدمين
const USER_ROLES = {
  SUPER_ADMIN: 'super_admin',
  HQ_ADMIN: 'hq_admin',
  CLUSTER_MANAGER: 'cluster_manager',
  WORKER: 'worker'
};

// مستويات المستخدمين
const USER_LEVELS = {
  HQ: 'HQ',
  CLUSTER: 'CLUSTER'
};

module.exports = {
  WORKFLOW_STATES,
  VALID_TRANSITIONS,
  USER_ROLES,
  USER_LEVELS
};